# Generated by Django 5.1.1 on 2024-09-09 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('measurable_goal', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_met', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('evaluation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='DecisionTracker.decision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
